# app/audio/engine.py
from abc import ABC, abstractmethod
from typing import Set

class IAudioEngine(ABC):
    @abstractmethod
    def ensure_loaded(self, path: str) -> None: ...
    @abstractmethod
    def play_loop(self, path: str) -> None: ...
    @abstractmethod
    def set_volume(self, path: str, volume: float) -> None: ...
    @abstractmethod
    def stop(self, path: str) -> None: ...
    @abstractmethod
    def unload(self, path: str) -> None: ...
    @abstractmethod
    def prune(self, retain_only: Set[str]) -> None: ...